#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Laboratorio4")]
public partial class PedidosDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Definiciones de métodos de extensibilidad
  partial void OnCreated();
  partial void InsertArticulo(Articulo instance);
  partial void UpdateArticulo(Articulo instance);
  partial void DeleteArticulo(Articulo instance);
  partial void InsertRubro(Rubro instance);
  partial void UpdateRubro(Rubro instance);
  partial void DeleteRubro(Rubro instance);
  partial void InsertCliente(Cliente instance);
  partial void UpdateCliente(Cliente instance);
  partial void DeleteCliente(Cliente instance);
  partial void InsertDeviceToken(DeviceToken instance);
  partial void UpdateDeviceToken(DeviceToken instance);
  partial void DeleteDeviceToken(DeviceToken instance);
  partial void InsertDomicilio(Domicilio instance);
  partial void UpdateDomicilio(Domicilio instance);
  partial void DeleteDomicilio(Domicilio instance);
  partial void InsertPedidoVenta(PedidoVenta instance);
  partial void UpdatePedidoVenta(PedidoVenta instance);
  partial void DeletePedidoVenta(PedidoVenta instance);
  partial void InsertPedidoVentaDetalle(PedidoVentaDetalle instance);
  partial void UpdatePedidoVentaDetalle(PedidoVentaDetalle instance);
  partial void DeletePedidoVentaDetalle(PedidoVentaDetalle instance);
  partial void InsertUsuario(Usuario instance);
  partial void UpdateUsuario(Usuario instance);
  partial void DeleteUsuario(Usuario instance);
  #endregion
	
	public PedidosDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Laboratorio4ConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public PedidosDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public PedidosDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public PedidosDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public PedidosDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Articulo> Articulo
	{
		get
		{
			return this.GetTable<Articulo>();
		}
	}
	
	public System.Data.Linq.Table<Rubro> Rubro
	{
		get
		{
			return this.GetTable<Rubro>();
		}
	}
	
	public System.Data.Linq.Table<Cliente> Cliente
	{
		get
		{
			return this.GetTable<Cliente>();
		}
	}
	
	public System.Data.Linq.Table<DeviceToken> DeviceToken
	{
		get
		{
			return this.GetTable<DeviceToken>();
		}
	}
	
	public System.Data.Linq.Table<Domicilio> Domicilio
	{
		get
		{
			return this.GetTable<Domicilio>();
		}
	}
	
	public System.Data.Linq.Table<PedidoVenta> PedidoVenta
	{
		get
		{
			return this.GetTable<PedidoVenta>();
		}
	}
	
	public System.Data.Linq.Table<PedidoVentaDetalle> PedidoVentaDetalle
	{
		get
		{
			return this.GetTable<PedidoVentaDetalle>();
		}
	}
	
	public System.Data.Linq.Table<Usuario> Usuario
	{
		get
		{
			return this.GetTable<Usuario>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Articulo")]
public partial class Articulo : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id_articulo;
	
	private string _codigo;
	
	private string _denominacion;
	
	private decimal _precioCompra;
	
	private decimal _precioVenta;
	
	private decimal _iva;
	
	private int _id_rubro;
	
	private EntitySet<PedidoVentaDetalle> _PedidoVentaDetalle;
	
	private EntityRef<Rubro> _Rubro;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_articuloChanging(int value);
    partial void Onid_articuloChanged();
    partial void OncodigoChanging(string value);
    partial void OncodigoChanged();
    partial void OndenominacionChanging(string value);
    partial void OndenominacionChanged();
    partial void OnprecioCompraChanging(decimal value);
    partial void OnprecioCompraChanged();
    partial void OnprecioVentaChanging(decimal value);
    partial void OnprecioVentaChanged();
    partial void OnivaChanging(decimal value);
    partial void OnivaChanged();
    partial void Onid_rubroChanging(int value);
    partial void Onid_rubroChanged();
    #endregion
	
	public Articulo()
	{
		this._PedidoVentaDetalle = new EntitySet<PedidoVentaDetalle>(new Action<PedidoVentaDetalle>(this.attach_PedidoVentaDetalle), new Action<PedidoVentaDetalle>(this.detach_PedidoVentaDetalle));
		this._Rubro = default(EntityRef<Rubro>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_articulo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id_articulo
	{
		get
		{
			return this._id_articulo;
		}
		set
		{
			if ((this._id_articulo != value))
			{
				this.Onid_articuloChanging(value);
				this.SendPropertyChanging();
				this._id_articulo = value;
				this.SendPropertyChanged("id_articulo");
				this.Onid_articuloChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo", DbType="NChar(15) NOT NULL", CanBeNull=false)]
	public string codigo
	{
		get
		{
			return this._codigo;
		}
		set
		{
			if ((this._codigo != value))
			{
				this.OncodigoChanging(value);
				this.SendPropertyChanging();
				this._codigo = value;
				this.SendPropertyChanged("codigo");
				this.OncodigoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_denominacion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string denominacion
	{
		get
		{
			return this._denominacion;
		}
		set
		{
			if ((this._denominacion != value))
			{
				this.OndenominacionChanging(value);
				this.SendPropertyChanging();
				this._denominacion = value;
				this.SendPropertyChanged("denominacion");
				this.OndenominacionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precioCompra", DbType="Decimal(6,2) NOT NULL")]
	public decimal precioCompra
	{
		get
		{
			return this._precioCompra;
		}
		set
		{
			if ((this._precioCompra != value))
			{
				this.OnprecioCompraChanging(value);
				this.SendPropertyChanging();
				this._precioCompra = value;
				this.SendPropertyChanged("precioCompra");
				this.OnprecioCompraChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precioVenta", DbType="Decimal(6,2) NOT NULL")]
	public decimal precioVenta
	{
		get
		{
			return this._precioVenta;
		}
		set
		{
			if ((this._precioVenta != value))
			{
				this.OnprecioVentaChanging(value);
				this.SendPropertyChanging();
				this._precioVenta = value;
				this.SendPropertyChanged("precioVenta");
				this.OnprecioVentaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iva", DbType="Decimal(4,2) NOT NULL")]
	public decimal iva
	{
		get
		{
			return this._iva;
		}
		set
		{
			if ((this._iva != value))
			{
				this.OnivaChanging(value);
				this.SendPropertyChanging();
				this._iva = value;
				this.SendPropertyChanged("iva");
				this.OnivaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_rubro", DbType="Int NOT NULL")]
	public int id_rubro
	{
		get
		{
			return this._id_rubro;
		}
		set
		{
			if ((this._id_rubro != value))
			{
				if (this._Rubro.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onid_rubroChanging(value);
				this.SendPropertyChanging();
				this._id_rubro = value;
				this.SendPropertyChanged("id_rubro");
				this.Onid_rubroChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Articulo_PedidoVentaDetalle", Storage="_PedidoVentaDetalle", ThisKey="id_articulo", OtherKey="id_articulo")]
	public EntitySet<PedidoVentaDetalle> PedidoVentaDetalle
	{
		get
		{
			return this._PedidoVentaDetalle;
		}
		set
		{
			this._PedidoVentaDetalle.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Rubro_Articulo", Storage="_Rubro", ThisKey="id_rubro", OtherKey="id_rubro", IsForeignKey=true)]
	public Rubro Rubro
	{
		get
		{
			return this._Rubro.Entity;
		}
		set
		{
			Rubro previousValue = this._Rubro.Entity;
			if (((previousValue != value) 
						|| (this._Rubro.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Rubro.Entity = null;
					previousValue.Articulo.Remove(this);
				}
				this._Rubro.Entity = value;
				if ((value != null))
				{
					value.Articulo.Add(this);
					this._id_rubro = value.id_rubro;
				}
				else
				{
					this._id_rubro = default(int);
				}
				this.SendPropertyChanged("Rubro");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_PedidoVentaDetalle(PedidoVentaDetalle entity)
	{
		this.SendPropertyChanging();
		entity.Articulo = this;
	}
	
	private void detach_PedidoVentaDetalle(PedidoVentaDetalle entity)
	{
		this.SendPropertyChanging();
		entity.Articulo = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Rubro")]
public partial class Rubro : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id_rubro;
	
	private string _codigo;
	
	private string _denominacion;
	
	private System.Nullable<int> _id_rubroPrimario;
	
	private EntitySet<Articulo> _Articulo;
	
	private EntityRef<Rubro> _Rubro2;
	
	private EntityRef<Rubro> _Rubro1;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_rubroChanging(int value);
    partial void Onid_rubroChanged();
    partial void OncodigoChanging(string value);
    partial void OncodigoChanged();
    partial void OndenominacionChanging(string value);
    partial void OndenominacionChanged();
    partial void Onid_rubroPrimarioChanging(System.Nullable<int> value);
    partial void Onid_rubroPrimarioChanged();
    #endregion
	
	public Rubro()
	{
		this._Articulo = new EntitySet<Articulo>(new Action<Articulo>(this.attach_Articulo), new Action<Articulo>(this.detach_Articulo));
		this._Rubro2 = default(EntityRef<Rubro>);
		this._Rubro1 = default(EntityRef<Rubro>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_rubro", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id_rubro
	{
		get
		{
			return this._id_rubro;
		}
		set
		{
			if ((this._id_rubro != value))
			{
				if (this._Rubro1.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onid_rubroChanging(value);
				this.SendPropertyChanging();
				this._id_rubro = value;
				this.SendPropertyChanged("id_rubro");
				this.Onid_rubroChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
	public string codigo
	{
		get
		{
			return this._codigo;
		}
		set
		{
			if ((this._codigo != value))
			{
				this.OncodigoChanging(value);
				this.SendPropertyChanging();
				this._codigo = value;
				this.SendPropertyChanged("codigo");
				this.OncodigoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_denominacion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string denominacion
	{
		get
		{
			return this._denominacion;
		}
		set
		{
			if ((this._denominacion != value))
			{
				this.OndenominacionChanging(value);
				this.SendPropertyChanging();
				this._denominacion = value;
				this.SendPropertyChanged("denominacion");
				this.OndenominacionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_rubroPrimario", DbType="Int")]
	public System.Nullable<int> id_rubroPrimario
	{
		get
		{
			return this._id_rubroPrimario;
		}
		set
		{
			if ((this._id_rubroPrimario != value))
			{
				this.Onid_rubroPrimarioChanging(value);
				this.SendPropertyChanging();
				this._id_rubroPrimario = value;
				this.SendPropertyChanged("id_rubroPrimario");
				this.Onid_rubroPrimarioChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Rubro_Articulo", Storage="_Articulo", ThisKey="id_rubro", OtherKey="id_rubro")]
	public EntitySet<Articulo> Articulo
	{
		get
		{
			return this._Articulo;
		}
		set
		{
			this._Articulo.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Rubro_Rubro", Storage="_Rubro2", ThisKey="id_rubro", OtherKey="id_rubro", IsUnique=true, IsForeignKey=false)]
	public Rubro Rubro2
	{
		get
		{
			return this._Rubro2.Entity;
		}
		set
		{
			Rubro previousValue = this._Rubro2.Entity;
			if (((previousValue != value) 
						|| (this._Rubro2.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Rubro2.Entity = null;
					previousValue.Rubro1 = null;
				}
				this._Rubro2.Entity = value;
				if ((value != null))
				{
					value.Rubro1 = this;
				}
				this.SendPropertyChanged("Rubro2");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Rubro_Rubro", Storage="_Rubro1", ThisKey="id_rubro", OtherKey="id_rubro", IsForeignKey=true)]
	public Rubro Rubro1
	{
		get
		{
			return this._Rubro1.Entity;
		}
		set
		{
			Rubro previousValue = this._Rubro1.Entity;
			if (((previousValue != value) 
						|| (this._Rubro1.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Rubro1.Entity = null;
					previousValue.Rubro2 = null;
				}
				this._Rubro1.Entity = value;
				if ((value != null))
				{
					value.Rubro2 = this;
					this._id_rubro = value.id_rubro;
				}
				else
				{
					this._id_rubro = default(int);
				}
				this.SendPropertyChanged("Rubro1");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_Articulo(Articulo entity)
	{
		this.SendPropertyChanging();
		entity.Rubro = this;
	}
	
	private void detach_Articulo(Articulo entity)
	{
		this.SendPropertyChanging();
		entity.Rubro = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cliente")]
public partial class Cliente : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id_cliente;
	
	private string _razonSocial;
	
	private string _cuit;
	
	private System.Nullable<decimal> _saldo;
	
	private EntitySet<Domicilio> _Domicilio;
	
	private EntitySet<PedidoVenta> _PedidoVenta;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_clienteChanging(int value);
    partial void Onid_clienteChanged();
    partial void OnrazonSocialChanging(string value);
    partial void OnrazonSocialChanged();
    partial void OncuitChanging(string value);
    partial void OncuitChanged();
    partial void OnsaldoChanging(System.Nullable<decimal> value);
    partial void OnsaldoChanged();
    #endregion
	
	public Cliente()
	{
		this._Domicilio = new EntitySet<Domicilio>(new Action<Domicilio>(this.attach_Domicilio), new Action<Domicilio>(this.detach_Domicilio));
		this._PedidoVenta = new EntitySet<PedidoVenta>(new Action<PedidoVenta>(this.attach_PedidoVenta), new Action<PedidoVenta>(this.detach_PedidoVenta));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_cliente", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id_cliente
	{
		get
		{
			return this._id_cliente;
		}
		set
		{
			if ((this._id_cliente != value))
			{
				this.Onid_clienteChanging(value);
				this.SendPropertyChanging();
				this._id_cliente = value;
				this.SendPropertyChanged("id_cliente");
				this.Onid_clienteChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_razonSocial", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string razonSocial
	{
		get
		{
			return this._razonSocial;
		}
		set
		{
			if ((this._razonSocial != value))
			{
				this.OnrazonSocialChanging(value);
				this.SendPropertyChanging();
				this._razonSocial = value;
				this.SendPropertyChanged("razonSocial");
				this.OnrazonSocialChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cuit", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string cuit
	{
		get
		{
			return this._cuit;
		}
		set
		{
			if ((this._cuit != value))
			{
				this.OncuitChanging(value);
				this.SendPropertyChanging();
				this._cuit = value;
				this.SendPropertyChanged("cuit");
				this.OncuitChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_saldo", DbType="Decimal(6,2)")]
	public System.Nullable<decimal> saldo
	{
		get
		{
			return this._saldo;
		}
		set
		{
			if ((this._saldo != value))
			{
				this.OnsaldoChanging(value);
				this.SendPropertyChanging();
				this._saldo = value;
				this.SendPropertyChanged("saldo");
				this.OnsaldoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Domicilio", Storage="_Domicilio", ThisKey="id_cliente", OtherKey="id_cliente")]
	public EntitySet<Domicilio> Domicilio
	{
		get
		{
			return this._Domicilio;
		}
		set
		{
			this._Domicilio.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_PedidoVenta", Storage="_PedidoVenta", ThisKey="id_cliente", OtherKey="id_cliente")]
	public EntitySet<PedidoVenta> PedidoVenta
	{
		get
		{
			return this._PedidoVenta;
		}
		set
		{
			this._PedidoVenta.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_Domicilio(Domicilio entity)
	{
		this.SendPropertyChanging();
		entity.Cliente = this;
	}
	
	private void detach_Domicilio(Domicilio entity)
	{
		this.SendPropertyChanging();
		entity.Cliente = null;
	}
	
	private void attach_PedidoVenta(PedidoVenta entity)
	{
		this.SendPropertyChanging();
		entity.Cliente = this;
	}
	
	private void detach_PedidoVenta(PedidoVenta entity)
	{
		this.SendPropertyChanging();
		entity.Cliente = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DeviceToken")]
public partial class DeviceToken : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _uuid;
	
	private string _model;
	
	private string _serial;
	
	private string _token;
	
	private System.DateTime _fechaCreacion;
	
	private System.Nullable<System.DateTime> _fechaExpiracion;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuuidChanging(int value);
    partial void OnuuidChanged();
    partial void OnmodelChanging(string value);
    partial void OnmodelChanged();
    partial void OnserialChanging(string value);
    partial void OnserialChanged();
    partial void OntokenChanging(string value);
    partial void OntokenChanged();
    partial void OnfechaCreacionChanging(System.DateTime value);
    partial void OnfechaCreacionChanged();
    partial void OnfechaExpiracionChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaExpiracionChanged();
    #endregion
	
	public DeviceToken()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uuid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int uuid
	{
		get
		{
			return this._uuid;
		}
		set
		{
			if ((this._uuid != value))
			{
				this.OnuuidChanging(value);
				this.SendPropertyChanging();
				this._uuid = value;
				this.SendPropertyChanged("uuid");
				this.OnuuidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_model", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
	public string model
	{
		get
		{
			return this._model;
		}
		set
		{
			if ((this._model != value))
			{
				this.OnmodelChanging(value);
				this.SendPropertyChanging();
				this._model = value;
				this.SendPropertyChanged("model");
				this.OnmodelChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_serial", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
	public string serial
	{
		get
		{
			return this._serial;
		}
		set
		{
			if ((this._serial != value))
			{
				this.OnserialChanging(value);
				this.SendPropertyChanging();
				this._serial = value;
				this.SendPropertyChanged("serial");
				this.OnserialChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_token", DbType="VarChar(36) NOT NULL", CanBeNull=false)]
	public string token
	{
		get
		{
			return this._token;
		}
		set
		{
			if ((this._token != value))
			{
				this.OntokenChanging(value);
				this.SendPropertyChanging();
				this._token = value;
				this.SendPropertyChanged("token");
				this.OntokenChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaCreacion", DbType="Date NOT NULL")]
	public System.DateTime fechaCreacion
	{
		get
		{
			return this._fechaCreacion;
		}
		set
		{
			if ((this._fechaCreacion != value))
			{
				this.OnfechaCreacionChanging(value);
				this.SendPropertyChanging();
				this._fechaCreacion = value;
				this.SendPropertyChanged("fechaCreacion");
				this.OnfechaCreacionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaExpiracion", DbType="Date")]
	public System.Nullable<System.DateTime> fechaExpiracion
	{
		get
		{
			return this._fechaExpiracion;
		}
		set
		{
			if ((this._fechaExpiracion != value))
			{
				this.OnfechaExpiracionChanging(value);
				this.SendPropertyChanging();
				this._fechaExpiracion = value;
				this.SendPropertyChanged("fechaExpiracion");
				this.OnfechaExpiracionChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Domicilio")]
public partial class Domicilio : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id_domicilio;
	
	private string _calle;
	
	private int _numero;
	
	private string _localidad;
	
	private string _latitud;
	
	private string _longitud;
	
	private string _tipo_domicilio;
	
	private int _id_cliente;
	
	private EntitySet<PedidoVenta> _PedidoVenta;
	
	private EntityRef<Cliente> _Cliente;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_domicilioChanging(int value);
    partial void Onid_domicilioChanged();
    partial void OncalleChanging(string value);
    partial void OncalleChanged();
    partial void OnnumeroChanging(int value);
    partial void OnnumeroChanged();
    partial void OnlocalidadChanging(string value);
    partial void OnlocalidadChanged();
    partial void OnlatitudChanging(string value);
    partial void OnlatitudChanged();
    partial void OnlongitudChanging(string value);
    partial void OnlongitudChanged();
    partial void Ontipo_domicilioChanging(string value);
    partial void Ontipo_domicilioChanged();
    partial void Onid_clienteChanging(int value);
    partial void Onid_clienteChanged();
    #endregion
	
	public Domicilio()
	{
		this._PedidoVenta = new EntitySet<PedidoVenta>(new Action<PedidoVenta>(this.attach_PedidoVenta), new Action<PedidoVenta>(this.detach_PedidoVenta));
		this._Cliente = default(EntityRef<Cliente>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_domicilio", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id_domicilio
	{
		get
		{
			return this._id_domicilio;
		}
		set
		{
			if ((this._id_domicilio != value))
			{
				this.Onid_domicilioChanging(value);
				this.SendPropertyChanging();
				this._id_domicilio = value;
				this.SendPropertyChanged("id_domicilio");
				this.Onid_domicilioChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_calle", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string calle
	{
		get
		{
			return this._calle;
		}
		set
		{
			if ((this._calle != value))
			{
				this.OncalleChanging(value);
				this.SendPropertyChanging();
				this._calle = value;
				this.SendPropertyChanged("calle");
				this.OncalleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numero", DbType="Int NOT NULL")]
	public int numero
	{
		get
		{
			return this._numero;
		}
		set
		{
			if ((this._numero != value))
			{
				this.OnnumeroChanging(value);
				this.SendPropertyChanging();
				this._numero = value;
				this.SendPropertyChanged("numero");
				this.OnnumeroChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_localidad", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string localidad
	{
		get
		{
			return this._localidad;
		}
		set
		{
			if ((this._localidad != value))
			{
				this.OnlocalidadChanging(value);
				this.SendPropertyChanging();
				this._localidad = value;
				this.SendPropertyChanged("localidad");
				this.OnlocalidadChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_latitud", DbType="VarChar(50)")]
	public string latitud
	{
		get
		{
			return this._latitud;
		}
		set
		{
			if ((this._latitud != value))
			{
				this.OnlatitudChanging(value);
				this.SendPropertyChanging();
				this._latitud = value;
				this.SendPropertyChanged("latitud");
				this.OnlatitudChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_longitud", DbType="VarChar(50)")]
	public string longitud
	{
		get
		{
			return this._longitud;
		}
		set
		{
			if ((this._longitud != value))
			{
				this.OnlongitudChanging(value);
				this.SendPropertyChanging();
				this._longitud = value;
				this.SendPropertyChanged("longitud");
				this.OnlongitudChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo_domicilio", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string tipo_domicilio
	{
		get
		{
			return this._tipo_domicilio;
		}
		set
		{
			if ((this._tipo_domicilio != value))
			{
				this.Ontipo_domicilioChanging(value);
				this.SendPropertyChanging();
				this._tipo_domicilio = value;
				this.SendPropertyChanged("tipo_domicilio");
				this.Ontipo_domicilioChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_cliente", DbType="Int NOT NULL")]
	public int id_cliente
	{
		get
		{
			return this._id_cliente;
		}
		set
		{
			if ((this._id_cliente != value))
			{
				if (this._Cliente.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onid_clienteChanging(value);
				this.SendPropertyChanging();
				this._id_cliente = value;
				this.SendPropertyChanged("id_cliente");
				this.Onid_clienteChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Domicilio_PedidoVenta", Storage="_PedidoVenta", ThisKey="id_domicilio", OtherKey="id_domicilio")]
	public EntitySet<PedidoVenta> PedidoVenta
	{
		get
		{
			return this._PedidoVenta;
		}
		set
		{
			this._PedidoVenta.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Domicilio", Storage="_Cliente", ThisKey="id_cliente", OtherKey="id_cliente", IsForeignKey=true)]
	public Cliente Cliente
	{
		get
		{
			return this._Cliente.Entity;
		}
		set
		{
			Cliente previousValue = this._Cliente.Entity;
			if (((previousValue != value) 
						|| (this._Cliente.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Cliente.Entity = null;
					previousValue.Domicilio.Remove(this);
				}
				this._Cliente.Entity = value;
				if ((value != null))
				{
					value.Domicilio.Add(this);
					this._id_cliente = value.id_cliente;
				}
				else
				{
					this._id_cliente = default(int);
				}
				this.SendPropertyChanged("Cliente");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_PedidoVenta(PedidoVenta entity)
	{
		this.SendPropertyChanging();
		entity.Domicilio = this;
	}
	
	private void detach_PedidoVenta(PedidoVenta entity)
	{
		this.SendPropertyChanging();
		entity.Domicilio = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PedidoVenta")]
public partial class PedidoVenta : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id_pedidoVenta;
	
	private System.DateTime _fechaEstimadaEntrega;
	
	private decimal _gastosEnvio;
	
	private string _estado;
	
	private bool _entregado;
	
	private System.DateTime _fechaPedido;
	
	private long _nroPedido;
	
	private decimal _subTotal;
	
	private decimal _montoTotal;
	
	private int _id_cliente;
	
	private int _id_domicilio;
	
	private EntitySet<PedidoVentaDetalle> _PedidoVentaDetalle;
	
	private EntityRef<Cliente> _Cliente;
	
	private EntityRef<Domicilio> _Domicilio;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_pedidoVentaChanging(int value);
    partial void Onid_pedidoVentaChanged();
    partial void OnfechaEstimadaEntregaChanging(System.DateTime value);
    partial void OnfechaEstimadaEntregaChanged();
    partial void OngastosEnvioChanging(decimal value);
    partial void OngastosEnvioChanged();
    partial void OnestadoChanging(string value);
    partial void OnestadoChanged();
    partial void OnentregadoChanging(bool value);
    partial void OnentregadoChanged();
    partial void OnfechaPedidoChanging(System.DateTime value);
    partial void OnfechaPedidoChanged();
    partial void OnnroPedidoChanging(long value);
    partial void OnnroPedidoChanged();
    partial void OnsubTotalChanging(decimal value);
    partial void OnsubTotalChanged();
    partial void OnmontoTotalChanging(decimal value);
    partial void OnmontoTotalChanged();
    partial void Onid_clienteChanging(int value);
    partial void Onid_clienteChanged();
    partial void Onid_domicilioChanging(int value);
    partial void Onid_domicilioChanged();
    #endregion
	
	public PedidoVenta()
	{
		this._PedidoVentaDetalle = new EntitySet<PedidoVentaDetalle>(new Action<PedidoVentaDetalle>(this.attach_PedidoVentaDetalle), new Action<PedidoVentaDetalle>(this.detach_PedidoVentaDetalle));
		this._Cliente = default(EntityRef<Cliente>);
		this._Domicilio = default(EntityRef<Domicilio>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pedidoVenta", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id_pedidoVenta
	{
		get
		{
			return this._id_pedidoVenta;
		}
		set
		{
			if ((this._id_pedidoVenta != value))
			{
				this.Onid_pedidoVentaChanging(value);
				this.SendPropertyChanging();
				this._id_pedidoVenta = value;
				this.SendPropertyChanged("id_pedidoVenta");
				this.Onid_pedidoVentaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaEstimadaEntrega", DbType="Date NOT NULL")]
	public System.DateTime fechaEstimadaEntrega
	{
		get
		{
			return this._fechaEstimadaEntrega;
		}
		set
		{
			if ((this._fechaEstimadaEntrega != value))
			{
				this.OnfechaEstimadaEntregaChanging(value);
				this.SendPropertyChanging();
				this._fechaEstimadaEntrega = value;
				this.SendPropertyChanged("fechaEstimadaEntrega");
				this.OnfechaEstimadaEntregaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gastosEnvio", DbType="Decimal(6,2) NOT NULL")]
	public decimal gastosEnvio
	{
		get
		{
			return this._gastosEnvio;
		}
		set
		{
			if ((this._gastosEnvio != value))
			{
				this.OngastosEnvioChanging(value);
				this.SendPropertyChanging();
				this._gastosEnvio = value;
				this.SendPropertyChanged("gastosEnvio");
				this.OngastosEnvioChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string estado
	{
		get
		{
			return this._estado;
		}
		set
		{
			if ((this._estado != value))
			{
				this.OnestadoChanging(value);
				this.SendPropertyChanging();
				this._estado = value;
				this.SendPropertyChanged("estado");
				this.OnestadoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_entregado", DbType="Bit NOT NULL")]
	public bool entregado
	{
		get
		{
			return this._entregado;
		}
		set
		{
			if ((this._entregado != value))
			{
				this.OnentregadoChanging(value);
				this.SendPropertyChanging();
				this._entregado = value;
				this.SendPropertyChanged("entregado");
				this.OnentregadoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaPedido", DbType="Date NOT NULL")]
	public System.DateTime fechaPedido
	{
		get
		{
			return this._fechaPedido;
		}
		set
		{
			if ((this._fechaPedido != value))
			{
				this.OnfechaPedidoChanging(value);
				this.SendPropertyChanging();
				this._fechaPedido = value;
				this.SendPropertyChanged("fechaPedido");
				this.OnfechaPedidoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nroPedido", DbType="BigInt NOT NULL")]
	public long nroPedido
	{
		get
		{
			return this._nroPedido;
		}
		set
		{
			if ((this._nroPedido != value))
			{
				this.OnnroPedidoChanging(value);
				this.SendPropertyChanging();
				this._nroPedido = value;
				this.SendPropertyChanged("nroPedido");
				this.OnnroPedidoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subTotal", DbType="Decimal(6,2) NOT NULL")]
	public decimal subTotal
	{
		get
		{
			return this._subTotal;
		}
		set
		{
			if ((this._subTotal != value))
			{
				this.OnsubTotalChanging(value);
				this.SendPropertyChanging();
				this._subTotal = value;
				this.SendPropertyChanged("subTotal");
				this.OnsubTotalChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_montoTotal", DbType="Decimal(6,2) NOT NULL")]
	public decimal montoTotal
	{
		get
		{
			return this._montoTotal;
		}
		set
		{
			if ((this._montoTotal != value))
			{
				this.OnmontoTotalChanging(value);
				this.SendPropertyChanging();
				this._montoTotal = value;
				this.SendPropertyChanged("montoTotal");
				this.OnmontoTotalChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_cliente", DbType="Int NOT NULL")]
	public int id_cliente
	{
		get
		{
			return this._id_cliente;
		}
		set
		{
			if ((this._id_cliente != value))
			{
				if (this._Cliente.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onid_clienteChanging(value);
				this.SendPropertyChanging();
				this._id_cliente = value;
				this.SendPropertyChanged("id_cliente");
				this.Onid_clienteChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_domicilio", DbType="Int NOT NULL")]
	public int id_domicilio
	{
		get
		{
			return this._id_domicilio;
		}
		set
		{
			if ((this._id_domicilio != value))
			{
				if (this._Domicilio.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onid_domicilioChanging(value);
				this.SendPropertyChanging();
				this._id_domicilio = value;
				this.SendPropertyChanged("id_domicilio");
				this.Onid_domicilioChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PedidoVenta_PedidoVentaDetalle", Storage="_PedidoVentaDetalle", ThisKey="id_pedidoVenta", OtherKey="id_pedidoVenta")]
	public EntitySet<PedidoVentaDetalle> PedidoVentaDetalle
	{
		get
		{
			return this._PedidoVentaDetalle;
		}
		set
		{
			this._PedidoVentaDetalle.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_PedidoVenta", Storage="_Cliente", ThisKey="id_cliente", OtherKey="id_cliente", IsForeignKey=true)]
	public Cliente Cliente
	{
		get
		{
			return this._Cliente.Entity;
		}
		set
		{
			Cliente previousValue = this._Cliente.Entity;
			if (((previousValue != value) 
						|| (this._Cliente.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Cliente.Entity = null;
					previousValue.PedidoVenta.Remove(this);
				}
				this._Cliente.Entity = value;
				if ((value != null))
				{
					value.PedidoVenta.Add(this);
					this._id_cliente = value.id_cliente;
				}
				else
				{
					this._id_cliente = default(int);
				}
				this.SendPropertyChanged("Cliente");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Domicilio_PedidoVenta", Storage="_Domicilio", ThisKey="id_domicilio", OtherKey="id_domicilio", IsForeignKey=true)]
	public Domicilio Domicilio
	{
		get
		{
			return this._Domicilio.Entity;
		}
		set
		{
			Domicilio previousValue = this._Domicilio.Entity;
			if (((previousValue != value) 
						|| (this._Domicilio.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Domicilio.Entity = null;
					previousValue.PedidoVenta.Remove(this);
				}
				this._Domicilio.Entity = value;
				if ((value != null))
				{
					value.PedidoVenta.Add(this);
					this._id_domicilio = value.id_domicilio;
				}
				else
				{
					this._id_domicilio = default(int);
				}
				this.SendPropertyChanged("Domicilio");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_PedidoVentaDetalle(PedidoVentaDetalle entity)
	{
		this.SendPropertyChanging();
		entity.PedidoVenta = this;
	}
	
	private void detach_PedidoVentaDetalle(PedidoVentaDetalle entity)
	{
		this.SendPropertyChanging();
		entity.PedidoVenta = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PedidoVentaDetalle")]
public partial class PedidoVentaDetalle : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id_pedidoVentaDetalle;
	
	private int _cantidad;
	
	private decimal _subTotal;
	
	private System.Nullable<double> _porcentajeDescuento;
	
	private System.Nullable<int> _id_articulo;
	
	private int _id_pedidoVenta;
	
	private EntityRef<Articulo> _Articulo;
	
	private EntityRef<PedidoVenta> _PedidoVenta;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_pedidoVentaDetalleChanging(int value);
    partial void Onid_pedidoVentaDetalleChanged();
    partial void OncantidadChanging(int value);
    partial void OncantidadChanged();
    partial void OnsubTotalChanging(decimal value);
    partial void OnsubTotalChanged();
    partial void OnporcentajeDescuentoChanging(System.Nullable<double> value);
    partial void OnporcentajeDescuentoChanged();
    partial void Onid_articuloChanging(System.Nullable<int> value);
    partial void Onid_articuloChanged();
    partial void Onid_pedidoVentaChanging(int value);
    partial void Onid_pedidoVentaChanged();
    #endregion
	
	public PedidoVentaDetalle()
	{
		this._Articulo = default(EntityRef<Articulo>);
		this._PedidoVenta = default(EntityRef<PedidoVenta>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pedidoVentaDetalle", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id_pedidoVentaDetalle
	{
		get
		{
			return this._id_pedidoVentaDetalle;
		}
		set
		{
			if ((this._id_pedidoVentaDetalle != value))
			{
				this.Onid_pedidoVentaDetalleChanging(value);
				this.SendPropertyChanging();
				this._id_pedidoVentaDetalle = value;
				this.SendPropertyChanged("id_pedidoVentaDetalle");
				this.Onid_pedidoVentaDetalleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="Int NOT NULL")]
	public int cantidad
	{
		get
		{
			return this._cantidad;
		}
		set
		{
			if ((this._cantidad != value))
			{
				this.OncantidadChanging(value);
				this.SendPropertyChanging();
				this._cantidad = value;
				this.SendPropertyChanged("cantidad");
				this.OncantidadChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subTotal", DbType="Decimal(6,2) NOT NULL")]
	public decimal subTotal
	{
		get
		{
			return this._subTotal;
		}
		set
		{
			if ((this._subTotal != value))
			{
				this.OnsubTotalChanging(value);
				this.SendPropertyChanging();
				this._subTotal = value;
				this.SendPropertyChanged("subTotal");
				this.OnsubTotalChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_porcentajeDescuento", DbType="Float")]
	public System.Nullable<double> porcentajeDescuento
	{
		get
		{
			return this._porcentajeDescuento;
		}
		set
		{
			if ((this._porcentajeDescuento != value))
			{
				this.OnporcentajeDescuentoChanging(value);
				this.SendPropertyChanging();
				this._porcentajeDescuento = value;
				this.SendPropertyChanged("porcentajeDescuento");
				this.OnporcentajeDescuentoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_articulo", DbType="Int")]
	public System.Nullable<int> id_articulo
	{
		get
		{
			return this._id_articulo;
		}
		set
		{
			if ((this._id_articulo != value))
			{
				if (this._Articulo.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onid_articuloChanging(value);
				this.SendPropertyChanging();
				this._id_articulo = value;
				this.SendPropertyChanged("id_articulo");
				this.Onid_articuloChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pedidoVenta", DbType="Int NOT NULL")]
	public int id_pedidoVenta
	{
		get
		{
			return this._id_pedidoVenta;
		}
		set
		{
			if ((this._id_pedidoVenta != value))
			{
				if (this._PedidoVenta.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onid_pedidoVentaChanging(value);
				this.SendPropertyChanging();
				this._id_pedidoVenta = value;
				this.SendPropertyChanged("id_pedidoVenta");
				this.Onid_pedidoVentaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Articulo_PedidoVentaDetalle", Storage="_Articulo", ThisKey="id_articulo", OtherKey="id_articulo", IsForeignKey=true)]
	public Articulo Articulo
	{
		get
		{
			return this._Articulo.Entity;
		}
		set
		{
			Articulo previousValue = this._Articulo.Entity;
			if (((previousValue != value) 
						|| (this._Articulo.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Articulo.Entity = null;
					previousValue.PedidoVentaDetalle.Remove(this);
				}
				this._Articulo.Entity = value;
				if ((value != null))
				{
					value.PedidoVentaDetalle.Add(this);
					this._id_articulo = value.id_articulo;
				}
				else
				{
					this._id_articulo = default(Nullable<int>);
				}
				this.SendPropertyChanged("Articulo");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PedidoVenta_PedidoVentaDetalle", Storage="_PedidoVenta", ThisKey="id_pedidoVenta", OtherKey="id_pedidoVenta", IsForeignKey=true)]
	public PedidoVenta PedidoVenta
	{
		get
		{
			return this._PedidoVenta.Entity;
		}
		set
		{
			PedidoVenta previousValue = this._PedidoVenta.Entity;
			if (((previousValue != value) 
						|| (this._PedidoVenta.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._PedidoVenta.Entity = null;
					previousValue.PedidoVentaDetalle.Remove(this);
				}
				this._PedidoVenta.Entity = value;
				if ((value != null))
				{
					value.PedidoVentaDetalle.Add(this);
					this._id_pedidoVenta = value.id_pedidoVenta;
				}
				else
				{
					this._id_pedidoVenta = default(int);
				}
				this.SendPropertyChanged("PedidoVenta");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuario")]
public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id_usuario;
	
	private string _nombreUsuario;
	
	private string _password;
	
	private string _nombreEmpleado;
	
	private string _apellidoEmpleado;
	
	private string _email;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_usuarioChanging(int value);
    partial void Onid_usuarioChanged();
    partial void OnnombreUsuarioChanging(string value);
    partial void OnnombreUsuarioChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnnombreEmpleadoChanging(string value);
    partial void OnnombreEmpleadoChanged();
    partial void OnapellidoEmpleadoChanging(string value);
    partial void OnapellidoEmpleadoChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    #endregion
	
	public Usuario()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_usuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id_usuario
	{
		get
		{
			return this._id_usuario;
		}
		set
		{
			if ((this._id_usuario != value))
			{
				this.Onid_usuarioChanging(value);
				this.SendPropertyChanging();
				this._id_usuario = value;
				this.SendPropertyChanged("id_usuario");
				this.Onid_usuarioChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreUsuario", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string nombreUsuario
	{
		get
		{
			return this._nombreUsuario;
		}
		set
		{
			if ((this._nombreUsuario != value))
			{
				this.OnnombreUsuarioChanging(value);
				this.SendPropertyChanging();
				this._nombreUsuario = value;
				this.SendPropertyChanged("nombreUsuario");
				this.OnnombreUsuarioChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string password
	{
		get
		{
			return this._password;
		}
		set
		{
			if ((this._password != value))
			{
				this.OnpasswordChanging(value);
				this.SendPropertyChanging();
				this._password = value;
				this.SendPropertyChanged("password");
				this.OnpasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreEmpleado", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string nombreEmpleado
	{
		get
		{
			return this._nombreEmpleado;
		}
		set
		{
			if ((this._nombreEmpleado != value))
			{
				this.OnnombreEmpleadoChanging(value);
				this.SendPropertyChanging();
				this._nombreEmpleado = value;
				this.SendPropertyChanged("nombreEmpleado");
				this.OnnombreEmpleadoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellidoEmpleado", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string apellidoEmpleado
	{
		get
		{
			return this._apellidoEmpleado;
		}
		set
		{
			if ((this._apellidoEmpleado != value))
			{
				this.OnapellidoEmpleadoChanging(value);
				this.SendPropertyChanging();
				this._apellidoEmpleado = value;
				this.SendPropertyChanged("apellidoEmpleado");
				this.OnapellidoEmpleadoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this.OnemailChanging(value);
				this.SendPropertyChanging();
				this._email = value;
				this.SendPropertyChanged("email");
				this.OnemailChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
