<?xml version="1.0" encoding="utf-8"?><Database Name="Laboratorio4" Class="PedidosDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-TOM\SQLEXPRESS;Initial Catalog=Laboratorio4;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Laboratorio4ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Articulo" Member="Articulos">
    <Type Name="Articulo">
      <Column Name="id_articulo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="codigo" Type="System.String" DbType="NChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="denominacion" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="precioCompra" Type="System.Decimal" DbType="Decimal(6,2) NOT NULL" CanBeNull="false" />
      <Column Name="precioVenta" Type="System.Decimal" DbType="Decimal(6,2) NOT NULL" CanBeNull="false" />
      <Column Name="iva" Type="System.Decimal" DbType="Decimal(4,2) NOT NULL" CanBeNull="false" />
      <Column Name="id_rubro" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Articulo_PedidoVentaDetalle" Member="PedidoVentaDetalles" ThisKey="id_articulo" OtherKey="id_articulo" Type="PedidoVentaDetalle" />
      <Association Name="Rubro_Articulo" Member="Rubro" ThisKey="id_rubro" OtherKey="id_rubro" Type="Rubro" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Cliente" Member="Clientes">
    <Type Name="Cliente">
      <Column Name="id_cliente" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="razonSocial" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="cuit" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="saldo" Type="System.Decimal" DbType="Decimal(6,2)" CanBeNull="true" />
      <Column Name="id_domicilio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_domicilioNegocio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Cliente_PedidoVenta" Member="PedidoVentas" ThisKey="id_cliente" OtherKey="id_cliente" Type="PedidoVenta" />
      <Association Name="Domicilio_Cliente" Member="Domicilio" ThisKey="id_domicilio" OtherKey="id_domicilio" Type="Domicilio" IsForeignKey="true" />
      <Association Name="Domicilio_Cliente1" Member="Domicilio1" ThisKey="id_domicilioNegocio" OtherKey="id_domicilio" Type="Domicilio" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Domicilio" Member="Domicilios">
    <Type Name="Domicilio">
      <Column Name="id_domicilio" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="calle" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="numero" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="localidad" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="latitud" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="longitud" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Domicilio_Cliente" Member="Clientes" ThisKey="id_domicilio" OtherKey="id_domicilio" Type="Cliente" />
      <Association Name="Domicilio_Cliente1" Member="Clientes1" ThisKey="id_domicilio" OtherKey="id_domicilioNegocio" Type="Cliente" />
      <Association Name="Domicilio_PedidoVenta" Member="PedidoVentas" ThisKey="id_domicilio" OtherKey="id_domicilio" Type="PedidoVenta" />
    </Type>
  </Table>
  <Table Name="dbo.PedidoVenta" Member="PedidoVentas">
    <Type Name="PedidoVenta">
      <Column Name="id_pedidoVenta" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fechaEstimadaEntrega" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="gastosEnvio" Type="System.Decimal" DbType="Decimal(6,2) NOT NULL" CanBeNull="false" />
      <Column Name="estado" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="entregado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="fechaPedido" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="nroPedido" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="subTotal" Type="System.Decimal" DbType="Decimal(6,2) NOT NULL" CanBeNull="false" />
      <Column Name="montoTotal" Type="System.Decimal" DbType="Decimal(6,2) NOT NULL" CanBeNull="false" />
      <Column Name="id_cliente" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_domicilio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="PedidoVenta_PedidoVentaDetalle" Member="PedidoVentaDetalles" ThisKey="id_pedidoVenta" OtherKey="id_pedidoVenta" Type="PedidoVentaDetalle" />
      <Association Name="Cliente_PedidoVenta" Member="Cliente" ThisKey="id_cliente" OtherKey="id_cliente" Type="Cliente" IsForeignKey="true" />
      <Association Name="Domicilio_PedidoVenta" Member="Domicilio" ThisKey="id_domicilio" OtherKey="id_domicilio" Type="Domicilio" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PedidoVentaDetalle" Member="PedidoVentaDetalles">
    <Type Name="PedidoVentaDetalle">
      <Column Name="id_pedidoVentaDetalle" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="cantidad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="subTotal" Type="System.Decimal" DbType="Decimal(6,2) NOT NULL" CanBeNull="false" />
      <Column Name="porcentajeDescuento" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="id_articulo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_pedidoVenta" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Articulo_PedidoVentaDetalle" Member="Articulo" ThisKey="id_articulo" OtherKey="id_articulo" Type="Articulo" IsForeignKey="true" />
      <Association Name="PedidoVenta_PedidoVentaDetalle" Member="PedidoVenta" ThisKey="id_pedidoVenta" OtherKey="id_pedidoVenta" Type="PedidoVenta" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Rubro" Member="Rubros">
    <Type Name="Rubro">
      <Column Name="id_rubro" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="codigo" Type="System.String" DbType="NChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="denominacion" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="id_rubroPrimario" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Rubro_Articulo" Member="Articulos" ThisKey="id_rubro" OtherKey="id_rubro" Type="Articulo" />
      <Association Name="Rubro_Rubro" Member="Rubros" ThisKey="id_rubro" OtherKey="id_rubroPrimario" Type="Rubro" />
      <Association Name="Rubro_Rubro" Member="Rubro1" ThisKey="id_rubroPrimario" OtherKey="id_rubro" Type="Rubro" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Usuario" Member="Usuarios">
    <Type Name="Usuario">
      <Column Name="id_usuario" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombreUsuario" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="nombreEmpleado" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="apellidoEmpleado" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>